//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogMonitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll to top.
        /// </summary>
        public static string Button_ScrollToTop_Off {
            get {
                return ResourceManager.GetString("Button_ScrollToTop_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrolled to top.
        /// </summary>
        public static string Button_ScrollToTop_On {
            get {
                return ResourceManager.GetString("Button_ScrollToTop_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cite.
        /// </summary>
        public static string Columns_Header_Cite {
            get {
                return ResourceManager.GetString("Columns_Header_Cite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Columns_Header_Level {
            get {
                return ResourceManager.GetString("Columns_Header_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Columns_Header_Message {
            get {
                return ResourceManager.GetString("Columns_Header_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Columns_Header_Time {
            get {
                return ResourceManager.GetString("Columns_Header_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show date.
        /// </summary>
        public static string Columns_ShowDate {
            get {
                return ResourceManager.GetString("Columns_ShowDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in external editor.
        /// </summary>
        public static string Command_ShowInExternalEditor {
            get {
                return ResourceManager.GetString("Command_ShowInExternalEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        public static string Default_lowercase {
            get {
                return ResourceManager.GetString("Default_lowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter highlighted rows.
        /// </summary>
        public static string FilterHighlight {
            get {
                return ResourceManager.GetString("FilterHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by level.
        /// </summary>
        public static string FilterLevel {
            get {
                return ResourceManager.GetString("FilterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by text.
        /// </summary>
        public static string FilterText {
            get {
                return ResourceManager.GetString("FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case sensitive.
        /// </summary>
        public static string FilterTextCaseSensitive {
            get {
                return ResourceManager.GetString("FilterTextCaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Monitor - {0} ({1} rows).
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Monitor - {0} - File not existed.
        /// </summary>
        public static string MainWindow_Title_FileNotExisted {
            get {
                return ResourceManager.GetString("MainWindow_Title_FileNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Monitor - {0} ({1} rows, shown {2}).
        /// </summary>
        public static string MainWindow_Title_Filtered {
            get {
                return ResourceManager.GetString("MainWindow_Title_Filtered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved logs.
        /// </summary>
        public static string SavedLogsTitle {
            get {
                return ResourceManager.GetString("SavedLogsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string SelectFileWindow_Browse {
            get {
                return ResourceManager.GetString("SelectFileWindow_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files list.
        /// </summary>
        public static string SelectFileWindow_Files {
            get {
                return ResourceManager.GetString("SelectFileWindow_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping list.
        /// </summary>
        public static string SelectFileWindow_Mappings {
            get {
                return ResourceManager.GetString("SelectFileWindow_Mappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string SelectFileWindow_Select {
            get {
                return ResourceManager.GetString("SelectFileWindow_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file.
        /// </summary>
        public static string SelectFileWindow_SelectedFile {
            get {
                return ResourceManager.GetString("SelectFileWindow_SelectedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected mapping.
        /// </summary>
        public static string SelectFileWindow_SelectedMapping {
            get {
                return ResourceManager.GetString("SelectFileWindow_SelectedMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File select.
        /// </summary>
        public static string SelectFileWindow_Title {
            get {
                return ResourceManager.GetString("SelectFileWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
    }
}
